### ISSUE TITLE
CI issues

### ISSUE THREAD

**Issue by thautwarm** [thautwarm/MLStyle.jl#108]
@Roger-luo Thanks for bumping up! 
I'd ask what is the wrong with the CI..
It seems that julia 1.0 cannot be download on windows-latest as the checksum failed..

**Comment by Roger-luo** [comment]
yeah, according to the slack discussion, there are some issues with windows right now since there are some delay on the server and the new julia 1.5.4 version. It should get fixed soon, we can just ignore that on ourside.
