### ISSUE TITLE
`if let` support

### ISSUE THREAD

**Issue by thautwarm** [thautwarm/MLStyle.jl#11]
Just like that in Rust.
```rust
if let (a, b) = data {
    # do something if the case is matched.
}
```

perspective syntax proposals:
```Julia
@when (a, b) = data begin
    # do something if the case is matched.
end
# or 
@if_let (a, b) = data begin
   # do something if the case is matched.
end
```
feel free to make a supplementary.

**Comment by findmyway** [comment]
https://clojuredocs.org/clojure.core/if-let

**Comment by findmyway** [comment]
https://clojuredocs.org/clojure.core/when-let

**Comment by thautwarm** [comment]
@findmyway I think `when-let` could be replaced by an `if-let` without `else` clause. The concept of `if-let` is better than Rust, I think, for it can accept not only a term of pattern matching but a normal bool expression is also valid.

So what's your ideal `if-let` syntax in Julia? @Roger-luo  prefers keyword `when`, and so am I, but I'd admit that this could be personal preference(maybe `if` causes the aesthetic fatigue for its frequently regular usage).

**Comment by findmyway** [comment]
If that is the case, `when` will be fine.
