### ISSUE TITLE
Expr template pattern?

### ISSUE THREAD

**Issue by Roger-luo** [thautwarm/MLStyle.jl#13]
In [MacroTools](https://github.com/MikeInnes/MacroTools.jl) there is `@capture` that accept an expression template and match the template. Here is a simple proposal to support expression pattern matching:

```Julia
@match expr begin
    name_::Int => "this is a type annotation"
    f_{x_}(vars__) => "this is a function accepts one type parameter"
    # etc...
end
```

The template syntax will just follow `@capture`, `_` means a variable, `__` means a list.

Or in `Match.jl`, there is 

```julia
@match expr begin
       Expr(:(::), [name, typename]) => (name, typename)
       _ => "failed"
end
```

This fails in MLStyle

**Comment by thautwarm** [comment]
Yes, this will fails for we don't supply a builtin destructor `Expr`. I'll be back to maintain MLStyle.jl once I finished new JIT tools in GraphEngine, which might take fewer than 2 weeks.

**Comment by thautwarm** [comment]
Now, full-featured!
@Roger-luo
