### ISSUE TITLE
Julia 1.7 Compat

### ISSUE THREAD

**Issue by rodinalex** [thautwarm/MLStyle.jl#134]
When trying to compile MLStyle on Julia 1.7, I get **ERROR: LoadError: type DataType has no field mutable**. It appears that the issue has been addressed by one of the contributors. Is there a plan to have a patch release any time soon? MLStyle is an excellent package and my package relies on it so it would be great to have the functionality back

**Comment by thautwarm** [comment]
Hello, MLStyle 0.4.10 fixes this issue.

```
(@v1.7) pkg> add MLStyle@0.4.10
```

Did the default installation give you another version of MLStyle?

**Comment by rodinalex** [comment]
Hi,
Thank you so much for the swift response! I put a minimum version restriction for MLStyle to ≥0.4.10 in my Project.toml and it appears to work now. I didn't realise that the patch added after the version release was applied to the version. I apologise for the confusion and thank you again for the amazing work!
