### ISSUE TITLE
Error UndefVarError: @compiler_options not defined

### ISSUE THREAD

**Issue by CourtA96** [thautwarm/MLStyle.jl#137]
The `@compiler_options` macro is no longer defined in `Base.Experimental`, which causes an UndefValError when precompiling MLStyle. I forked the package and changed every line that read:

```
if isdefined(Base, :Experimental)
    @eval Base.Experimental.@compiler_options optimize=0 compile=min infer=no
end
```

to

```
if isdefined(Base.Experimental, :compiler_options)
    @eval Base.Experimental.@compiler_options optimize=0 compile=min infer=no
end
```

and that seemed to fix the issue for me. I don't know if this fix impacts the functioning of the package though.

**Comment by thautwarm** [comment]
Hello. I've just started working on this. I found in the master branch of julia repo, stdlibs are still referencing this under `@compiler_options` under `Base.Experimental`. Could you please provide more information about your working environment?

**Comment by CourtA96** [comment]
I was using the default environment for Julia 1.3.1. The older versions of Julia don't have @compiler_options defined in Base.Experimental.  When I raised this issue, I hadn't realized that I had reverted to an older version, so I assumed @compiler_options must have been deleted. Now that I'm back to Julia 1.6.1 the error doesn't occur.

I'm sorry for the confusion!

**Comment by thautwarm** [comment]
@hofmannmartin can you try the latest version of MLStyle?

**Comment by hofmannmartin** [comment]
works like a charm with the latest Version. Thank you.

**Comment by thautwarm** [comment]
@CourtA96 I think 0.4.13 works for Julia 1.0-1.8, could you help verify this? I want to close this issue.

**Comment by CourtA96** [comment]
Yes, it's working for me now in Julia 1.3.1. Thanks!
