### ISSUE TITLE
use = instead of in for the as-pattern? 

### ISSUE THREAD

**Issue by MasonProtter** [thautwarm/MLStyle.jl#17]
It might make sense to use `=` or `:=` for the as-pattern instead of `in`. I mean, this is essentially assignment inside a pattern, right? Could look like eg:
```julia
@match (1, 2) begin
    c := (a, b) => c[1] == a && c[2] == b
end
```

**Comment by thautwarm** [comment]
@MasonProtter 
Thanks for your feedback!

Using `in`  is actually a workaround.  In the dev branch, `in` is removed and the **And Pattern** is introduced to provide related functionalities:

```julia
@match (1, 2) begin
    c && (a, b) => c[1] == a && c[2] == b
end
```
