### ISSUE TITLE
`@match :(if true; end) :(if true; end) => 1` fails

### ISSUE THREAD

**Issue by jariji** [thautwarm/MLStyle.jl#188]
This fails to match. Is this expected?

```jl
@match :(if true; end) :(if true; end) => 1
```

**Comment by jariji** [comment]
Bump

**Comment by thautwarm** [comment]
This is because line numbers are automatically inserted into your quotations:
```julia
@match :(if true; end) :(if true; $(lines...) end) => lines

1-element view(::Vector{Any}, 1:1) with eltype Any:
 :(#= REPL[4]:1 =#)
```

MLStyle uses a strict match so that we can distinguish the cases that involve subtle differences.
