### ISSUE TITLE
`@match` gives the incorrect results when types are passed in as values

### ISSUE THREAD

**Issue by jonniediegelman** [thautwarm/MLStyle.jl#189]
Given the following result for matching on values
```julia
julia> x = 2;

julia> @match x begin
           1 => "One!"
           2 => "Two!"
           _ => "Many!"
       end
"Two!"
```
I'd expect the following to similarly match on values and output  `"I'm a Type{Float64}!"`:
```julia
julia> T = Float64;

julia> @match T begin
           Int => "I'm a Type{Int}!"
           Float64 => "I'm a Type{Float64}!"
           _ => "I don't know what I am!"
       end
```
Instead it outputs `"I'm a Type{Int}!"`. I now know that the recommended way of doing this is
```julia
julia> @match T begin
           ::Type{Int} => "I'm a Type{Int}!"
           ::Type{Float64} => "I'm a Type{Float64}!"
           _ => "I don't know what I am!"
       end
```
but still the other version just silently gives the incorrect result and it can be pretty tricky to debug code that has this mistake in it. And it's still not really clear to me _why_ the other version is wrong.

If it's not possible to get type-as-value version working, would it at least be possible to throw an error when a type is passed in as a value like this?

**Comment by jariji** [comment]
It's because in the first example those are [literal patterns](https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#literal-patterns) because it's a `2`, whereas `Float64` is a [capturing pattern](https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#capturing-patterns) because it's a symbol.

**Comment by jonniediegelman** [comment]
I see. So `Float64` is interpreted as just some variable in this case. This does indeed happen without types:
```julia
julia> one = 1; two = 2;

julia> x = two;

julia> @match x begin
           one => "One!"
           two => "Two!"
           _ => "Many!"
       end
"One!"
```
Maybe an error could be thrown if two patterns are the "same" on the left side?

**Comment by jariji** [comment]
That's like https://github.com/thautwarm/MLStyle.jl/issues/127

**Comment by ShalokShalom** [comment]
So can we close this one?

**Comment by thautwarm** [comment]
I'd close this but pin it as it is a FAQ.
If anyone has a different idea, you could just have discussions here which is helpful for other users with this issue.

**Comment by ShalokShalom** [comment]
I would just include an appropriate error message?

**Comment by thautwarm** [comment]
> I would just include an appropriate error message?

Do you have any design ideas? MLStyle can detect redundant patterns in some cases, but I'm not sure if I should mark things as intentional or unexpected.

**Comment by jariji** [comment]
Is there any benefit to allowing redundant cases (https://github.com/thautwarm/MLStyle.jl/issues/127)?
