### ISSUE TITLE
macro capture

### ISSUE THREAD

**Issue by Roger-luo** [thautwarm/MLStyle.jl#37]
To make use of the fast speed of this package, a capture macro like MacroTools would be preferred. And instead of underscore, we could use current match's expr template style.

**Comment by thautwarm** [comment]
like this?
```julia
@capture ex begin
    f($x, y) => x  # AST pattern
   $(Expr(:meta, a)) => a # Expr pattern
end
```
Does it really make sense for we already have the following?

```julia
@match ex begin
  :(f($x, y)) => x
   Expr(:meta, a) => a
end
```

It seems that `@capture` just simplify AST pattern a little.

**Comment by Roger-luo** [comment]
Umm, it is just an eye candy of `@match` in MLStyle, and has similar interface of regex, e.g

```julia
@capture <template> <expr>

@capture :(1 + $x + $y) 1 + a + b
```

this will return a tuple: `(:a, :b)`

**Comment by thautwarm** [comment]
The problem is `$` inside a Quote would be evaluated eagerly if it's not an argument of macrocall, so if you want to use such a @capture macro, you cannot share a common template with multiple callsites.

```julia
template = :(1 + $a + $b) # wrong! a, b would inserted here
```
So you cannt do these:
```
@capture $template ex1
@capture $template ex2
```
If we quote an Expr twice `:(:($a))`, the $ would then be preserved.

**Comment by thautwarm** [comment]
@Roger-luo Would this be sufficient?

https://thautwarm.github.io/MLStyle.jl/latest/tutorials/capture/
