### ISSUE TITLE
clarify package motivation, purpose, and scope in the readme

### ISSUE THREAD

**Issue by tpapp** [thautwarm/MLStyle.jl#39]
It would be great if you could write a paragraph or two in the README about what motivated this package, what it does (broadly), and what the underlying design principle is.

**Comment by thautwarm** [comment]
Thank you! I'll finish it as soon as possible!

**Comment by thautwarm** [comment]
@tpapp Hi, friend, could you please have a glance of current README?

**Comment by tpapp** [comment]
It clarifies a lot. Thanks!

**Comment by thautwarm** [comment]
You're welcome! Thanks for your suggestions! :+1:
