### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by findmyway** [thautwarm/MLStyle.jl#4]
The `@def` macro in the Incoming Features is very interesting:

```
@def f {
   ((a, b), true)   => <body1>
   (nothing, false) => <body2>

   _                => <body3>
}
```

I'm wondering if you can also support state sharing between different method implementations? Like bellow:

```
@def f {
    let x = 1
       ((a, b), true)   => <body1>
       (nothing, false) => <body2>

       _                => <body3>
}
```

Thanks!

**Comment by thautwarm** [comment]
It seems kind of strange but implementation is not that difficult. 
Any example to explain the use case?

**Comment by lwoo1999** [comment]
Sometimes, different branch needs to share common code.

Example in haskell:

```hs
f :: a -> b
f x = case x of
  ... -> g ...
  ... -> g ...
  ...
  ... -> g ...
  where g = ...
```

**Comment by findmyway** [comment]
Closed since it's easy to add an outside wrapper
