### ISSUE TITLE
Optional ast match ?

### ISSUE THREAD

**Issue by jonathanBieler** [thautwarm/MLStyle.jl#61]
@thautwarm  Sorry that's more a basic question than an issue. I'm playing a bit with the package and it looks super interesting. I'm trying to change the ast match example from the doc to include where statements and return type annotation:

```julia

ast = quote
    function f(a::Int, b::Float16, d::T)::Int128 where {T}
      let d = a + b + c, e = x -> 2x + d
          e(d)
      end
    end
end

@match ast begin
    quote
        $(::LineNumberNode)
        function $funcname($(args...))::$(out) where {$(cov)}
            $(block...)
        end
    end =>
         Dict(:funcname => funcname,
              :args     => args,
              :out      => out,
              :cov      => cov,
        )
end
```

Is it possible to say that the `where {$(cov)}` for example is optional ? Or do I need to make patterns for each subcases ?

Thanks!

**Comment by thautwarm** [comment]
Thanks for spending time with MLStyle.jl and us!
About your question, the solution is
```julia
@match ast begin
           :(
               function $funcname($(args...))::$out where {$(cov...)}
                   $(block...)
               end
           ) =>
                Dict(:funcname => funcname,
                     :args     => args,
                     :out      => out,
                     :cov      => cov)
end
```
Notice the ` where {$(cov...)}`, it's documented in Julia official docs:
https://docs.julialang.org/en/v1/manual/metaprogramming/#Splatting-interpolation-1

Any time you feel confused about MLStyle,jl, just remember it just help you to **destruct/deconstruct things just as how they're constructed**:

```julia
where_vars = [:x, :y]
ast =  :(
             function f(a::Int, b::Float16, d::T)::Int128 where {$(where_vars...)}
                   let d = a + b + c, e = x -> 2x + d
                      e(d)
                   end
             end
        )

@match ast begin
           :(
              function $funcname($(args...))::$out where {$(cov...)}
                   $(block...)
              end
            ) => where_vars == cov
 end # => true
```

Additionally, the AST of 
```julia
function f() where {}
end
```
is not same as
```julia
function f()
end
```
, although they're the same in semantics. You can use `dump` to verify this fact.

**Comment by thautwarm** [comment]
Another underline knowledge is that the AST of `function f() where {T}...` is the same as `function f() where T`, a bit tricky but does contribute to the consistency of Julia language.

And a useful feature you might like to know is the `Or-pattern`,
```julia
f1node = :(function f() where {}; end)
f2node = :(function f() where T; end)
f3node = :(function f() where {T1, T2}; end)


extract_where(node) = @match node begin
    :(function f() where {$(cov...)}; $(_...) end) ||
    :(function f(); $(_...) end) && Do(cov = []) => cov 
 end

extract_where(f1node) # []
extract_where(f2node) # [:T]
extract_where(f3node) # [:T1, :T2]
```

**Comment by thautwarm** [comment]
About Or-Patterns: https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern/#Or-Pattern-1

**Comment by jonathanBieler** [comment]
Thanks for the detailed answer, I think the Or pattern does the trick. This is so much nicer that play with the head and args.
