### ISSUE TITLE
your work is well appreciated

### ISSUE THREAD

**Issue by JeffreySarnoff** [thautwarm/MLStyle.jl#65]
This matters, and your effort drives other's active imagination as software is designed.

Best,
Jeffrey Sarnoff

**Comment by Roger-luo** [comment]
It's a pity @thautwarm missed this year's JuliaCon, wish he could catch up next year's.

**Comment by thautwarm** [comment]
Thank you very much. I'm pleased that this work is recognized by people from Julia community!
