### ISSUE TITLE
Inconsistent sequential unpacking error ?

### ISSUE THREAD

**Issue by jonathanBieler** [thautwarm/MLStyle.jl#71]
I'm trying to match assignment expressions like `x = 2` or `x,y = 1,2`. I've tried the following but I'm getting a `SyntaxError("Sequential unpacking can only be performed once at most.")`, I guess because of the two `...` on the same line.

```julia
@match :(x,y = 1,2) begin
    :( 
        $x, $(rhs...) = $(y...) 
    ) => (x,)
end
```

However the same code with a `quote` block works just fine, which seems a bit inconsistent:

```julia
@match quote x,y = 1,2 end begin 
    quote
        $(::LineNumberNode)
        $x, $(rhs...) = $(y...) 
    end => (x,)
end
```

Is there a good reason why one is working but not the other ?

**Comment by inkydragon** [comment]
````julia
julia> :(x,y = 1,2) |> dump
Expr
  head: Symbol tuple
  args: Array{Any}((3,))
    1: Symbol x
    2: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Symbol y
        2: Int64 1
    3: Int64 2

julia> quote x,y = 1,2 end |> dump
Expr
  head: Symbol block
  args: Array{Any}((2,))
    1: LineNumberNode
      line: Int64 1
      file: Symbol REPL[3]
    2: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Expr
          head: Symbol tuple
          args: Array{Any}((2,))
            1: Symbol x
            2: Symbol y
        2: Expr
          head: Symbol tuple
          args: Array{Any}((2,))
            1: Int64 1
            2: Int64 2
````

Because in the first case, julia think there is only a tuple which has 3 items.

**Comment by thautwarm** [comment]
`$x, $(rhs...) = $(y...) ` should be `($x, $(rhs...)) = ($(y...), )`.
I'll explain this to you tomorrow. Too late now.

**Comment by thautwarm** [comment]
IIRC, your question will get answered naturally if you try following codes:

```
x = :x
rhs = [:r1, :r2]
y = [:y1, :y2]
dump(:($x, $(rhs...) = $(y...) ))
dump(:($x, $(rhs...) = $(y...); 1;))
```

Whether it's inconsistent depends your mind(mental model), but anyway the ascription has no concerns to MLStyle(Julia syntax instead).

Due to the expectation of being concise and convenient, Julia discarded a few consistencies, causing "this inconsistency", IMAO.

**Comment by jonathanBieler** [comment]
Any idea how to capture assignments then ?

**Comment by thautwarm** [comment]
This works:
```julia
@match stmt begin
    :( $lhs = $rhs ) => ...
end
```

When both LHS and RHS of your assignment is a `Expr(:tuple, ...)`, and you want to deconstruct LHS as `$x, $(rhs...)` and deconstruct RHS as a sequence, this is okay:

```julia
@match stmt begin
   :(($x, $(rhs...)) = ($(y...), )) => (x, rhs, y)
end
``` 

Some examples:
```julia
julia> f(stmt) = @match stmt begin
           :(($x, $(rhs...)) = ($(y...), )) => (x, rhs, y)
           _ => ()
       end
f (generic function with 2 methods)

julia> stmts = quote
           a, b = 2, 3
       end
quote
    #= REPL[43]:2 =#
    (a, b) = (2, 3)
end

julia> f(stmts.args[2])
(:a, Any[:b], Any[2, 3])
```

**Note!!!** I don't know if you've understood what we said above, you should aware `:(x,y = 1,2)` has the shape `Expr(:tuple, ...)`, while what you expect(an assignment) is `:(x, y=1, 2;)`.

**Comment by thautwarm** [comment]
@jonathanBieler Did this answer you question?

**Comment by jonathanBieler** [comment]
Thanks, I think I got it:

```julia
match_assigment(ex) = @match ex begin
    :(
        ($first, $(lhs...)) = ($(rhs...), )
    ) && Do(first = (first,)) ||
    :( 
        $lhs = $rhs 
    ) && Do(first = (), lhs = (lhs,)) ||
    _ && Do(first = (), lhs = ()) =>
        Symbol[first..., lhs...]
end
```

I'm also using `Meta.parse("x,y = 1,2")` to build my expression, it seems to do the right thing.

**Comment by thautwarm** [comment]
Glad to see you've made it. IMO you might prefer `Expr(:(=), lhs, rhs)`? Matching things literally is not always the most simple solution.

I think what you want is:

```julia
match_assigment(ex) = @match ex begin
        Expr(:(=), Expr(:tuple, (lhs && Many(::Symbol))...),   _) => lhs
        Expr(:(=), l::Symbol, _) => [l]
       _ => Symbol[]
end

julia> match_assigment((quote a, b, c = 2 end).args[2])
3-element view(::Array{Any,1}, 1:3) with eltype Any:
 :a
 :b
 :c

julia> match_assigment((quote a = 1 end).args[2])
1-element Array{Symbol,1}:
 :a

julia> match_assigment((quote 1 end).args[2])
0-element Array{Symbol,1}
```

> I'm also using Meta.parse("x,y = 1,2") to build my expression, it seems to do the right thing.

Yes, it works. The reason why `:(x, y=1, 2)` didn't work should be given by Julia developers...
