### ISSUE TITLE
Expr pattern is not working with Float

### ISSUE THREAD

**Issue by Roger-luo** [thautwarm/MLStyle.jl#73]
MWE:

```jl
function foo(ex)
    @match ex begin
        Expr(:call, sin, 2π) => 0
        _ => "unknown"
    end
end
```

it seems there is no way to eval numerics in the pattern?

**Comment by Roger-luo** [comment]
should be `&2π`, this part is a bit intuitive to me. I'm wondering if it is possible to just write `2π` without making ambiguity?

**Comment by thautwarm** [comment]
It's `&(2π)`.

> I'm wondering if it is possible to just write 2π without making ambiguity?

It's impossible, I remember we used to discuss about this.

`Expr(:call, 2, :π)` shouldn't match `Expr(:call, 2, π)`, does it make sense?

- `:π` is a pattern to match a symbol `:π`,
- `π` is a pattern to capture the positional value as variable `π`, 
- `&π` is a pattern to match the positional value with the variable `π` in current scope.

**Comment by Roger-luo** [comment]
yeah, closed.
