### ISSUE TITLE
@as_record slows down the loading

### ISSUE THREAD

**Issue by AIxer** [thautwarm/MLStyle.jl#92]
Perhaps some optimizations could be made to speed up the startup process. 😃

**Comment by thautwarm** [comment]
I have to delay the implementation. Maybe after 7/20..

**Comment by thautwarm** [comment]
@AIxer Now the master branch should be quite fast when defining new records.

See https://github.com/thautwarm/MLStyle.jl/blob/941c14b711a73e084cea296c6835fbb8fa86b6ff/src/Record.jl#L26

Thanks for pointing out this possibility.
