### ISSUE TITLE
Feature request: one-liner @match syntax

### ISSUE THREAD

**Issue by MasonProtter** [thautwarm/MLStyle.jl#93]
Hi, I wonder if there's a case to be made for being able to write 
```julia
@match x pat => result
```
or
```julia
@match x {pat => result}
```
because the current alternatives that work:
```julia
@match x begin pat => result end
```
and
```julia
@match x (pat => result;)
```
are a little unsightly for one-liners imo.

**Comment by thautwarm** [comment]
Thanks for your request.
I think supporting `@match x pat => result`  is better.
The standalone curly brace is nearly an alien syntax to Julia(I guess it exists for the deprecated cell arrays), I want to get rid of it if using it introduces no big benefit.
I can do this in the weekend, or @inkydragon have time for this now?

**Comment by thautwarm** [comment]
Beside of `@match value pattern=>expr`, I think there's another closely-related one-liner match.

In [Match.jl](http://kmsquire.github.io/Match.jl/latest/#Extract-first-element,-rest-of-vector-1), you can use `@match(value, pattern)` to enter new variables and use them later:
```julia
@match(a, [hd, tl...])
println(hd, tl)
```

I want to know how people feel about those 2 forms of one-liner match.

**Comment by MasonProtter** [comment]
> The standalone curly brace is nearly an alien syntax to Julia(I guess it exists for the deprecated cell arrays), I want to get rid of it if using it introduces no big benefit.

It's actually mostly reserved so that macros can use it if they wish (or if Base decides they've found a good use for it), but yeah, I'm not tied to it. I just though it might be nice to offer an alternative to `begin end` and use `{}` instead. I think `@match x pat => result` is fine.

> In Match.jl, you can use @match(value, pattern) to enter new variables and use them later

Could be useful, but I think it might be a bit confusing as it's a slightly different meaning than the current match syntax. I think in this case, maybe it'd be better to just make a new macro, i.e.
```julia
@destruct(a, [hd, tl...])
```
which is equivlanent to 
```julia
hd, tl = @match a [hd, tl...] => (hd, tl)
```

**Comment by thautwarm** [comment]
> Could be useful, but I think it might be a bit confusing as it's a slightly different meaning than the current match syntax. I think in this case, maybe it'd be better to just make a new macro, i.e.

I agree with you.

However MLStyle is already quite big so I want to get rid of introducing new stuffs.

Instead, I hope other packages can leverage MLStyle to do this.

MLStyle already provides the infrastructure for syntax customizations and codegen optimizations.
Instead of only a user interface library, it's also a utility one.

I'll find some time to document how to use MLStyle as a **back end** for higher-level/more user-friendly pattern matching features.

> ```julia
> hd, tl = @match a [hd, tl...] => (hd, tl)
> ```

This is a little bit annoying, as there're a lot of self repetition..

MLStyle actually encourages you to write assignment-less code, I hope users could write code like

```julia
@when [hd, tl...] = a begin
    # do some with 'hd' and 'tl'
@otherwise
    # if not matched
end
```
